services:
  rest-cxx:
    image: ${REGISTRY_HOST}/rest-cxx/${CI_COMMIT_BRANCH}
#    build:
#      context: ../rest_server
#      dockerfile: ../docker/cxx/Dockerfile
#    environment:
#      DB_URL: postgres://node:node@swarm.next:15001/aip_data?sslmode=disable
#      PORT: 8080
#    ports:
#      - 8080:8080

  simpletracker:
    image: ${REGISTRY_HOST}/simpletracker/${CI_COMMIT_BRANCH}
#    build:
#      context: ../simpleTaskTrackerWebApp
#      dockerfile: ../docker/java/Dockerfile

  python-api:
    image: ${REGISTRY_HOST}/python-flask-api/${CI_COMMIT_BRANCH}
    build:
      context: ../SimpleFlaskAPI
      dockerfile: ../docker/python/Dockerfile
