networks:
  ingress-routing:
    external: true
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--core.defaultRuleSyntax=v2"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=ingress-routing"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.https.http.tls=true"
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=pugachev.ra@yandex.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt.acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencryt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.domains[0].main=traefik.simple-track.ru"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.rule=Host(`traefik.simple-track.ru`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"

    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - ingress-routing

volumes:
  letsencryt:
    name: letsencryt