on:
  workflow_dispatch:
  push: { branches: [main, master, release] }

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - env:
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          DOCKER_TAG: ${{ github.sha }}
        run: |
          docker buildx bake -f docker/docker-compose.yml --push --set *.args.ENV_FILE=.env
#          docker buildx imagetools create -t $DOCKER_REPO:latest $DOCKER_REPO:$DOCKER_TAG
