name: Build CPP REST Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build using Dockerfile.build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.build
        push: false
        tags: cpp-rest-server:latest
