on:
  workflow_dispatch:
  push: { branches: [main, master, release] }

jobs:
#  build-push-deploy:
#    runs-on: ubuntu-24.04
#    permissions: { contents: read, packages: write }
#    steps:
#      - uses: actions/checkout@v3
#      - uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - uses: docker/setup-buildx-action@v2
#      - run: |
#          cd docker
#          export $(grep -v '^#' .env | xargs)
#          export REPOSITORY_OWNER=${{ github.repository_owner}}
#          export REGISTRY_HOST=ghcr.io/${REPOSITORY_OWNER,,}/${{ github.event.repository.name }}
#          export CI_COMMIT_BRANCH=${{ github.ref_name }}
#          docker buildx bake -f docker-compose.yml --push

  deploy-in-swarm:
#    needs: build-push-deploy
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SERVER_SSH_KEY_PUB }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        export $(grep -v '^#' .env | xargs)
        export REPOSITORY_OWNER=${{ github.repository_owner}}
        export REGISTRY_HOST=ghcr.io/${REPOSITORY_OWNER,,}/${{ github.event.repository.name }}
        export CI_COMMIT_BRANCH=${{ github.ref_name }}
    - run: |
        echo "variable REGISTRY_HOST=${REGISTRY_HOST}"
        echo "variable CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}"
        echo "${{ secrets.SERVER_AUTHORIZE_REGISRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker context create remote-server --docker "host=ssh://${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}"
        docker context use remote-server 
        docker compose -f ./docker/docker-compose-deploy.yaml config
        docker stack deploy --compose-file ./docker/docker-compose-deploy.yaml --with-registry-auth -d stack_my_app 
