on:
  workflow_dispatch:
  push: { branches: [main,master, release] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: rest_server
          file: docker/Dockerfile.build
          push: false
          tags: cpp-rest-server:latest
